

development:
  adapter: postgresql
  encoding: unicode
  database: recispeak_development
  pool: 5
  username: nicholasbundy
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: recispeak_test
  pool: 5
  username: nicholasbundy
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: recispeak_production
  pool: 5
  username: nicholasbundy
  password:
